Garage 2.0/Models/VehicleTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage_2._0.Data;
using Garage3._0.Core.Entities;
using Garage3._0.Core.ViewModels;

namespace Garage_2._0.Models
{
    public class VehicleTypesController : Controller
    {
        private readonly Garage_2_0Context _context;

        public VehicleTypesController(Garage_2_0Context context)
        {
            _context = context;
        }

        // GET: VehicleTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.VehicleType.Select(v => new VehicleTypeViewModel
            {
                Id = v.Id,
                TypeName = v.TypeName

            }).ToListAsync());

            //return _context.VehicleType != null ? 
            //              View(await _context.VehicleType.ToListAsync()) :
            //              Problem("Entity set 'Garage_2_0Context.VehicleType'  is null.");
        }

        // GET: VehicleTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VehicleType == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // GET: VehicleTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VehicleTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TypeName")] VehicleTypeViewModel vehicleView /*VehicleType vehicleType*/)
        {
            if (ModelState.IsValid)
            {
                var vehicleType = new VehicleType
                {
                    Id = vehicleView.Id,
                    TypeName = vehicleView.TypeName
                };

                _context.Add(vehicleType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleView);
        }

        // GET: VehicleTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VehicleType == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType.FindAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }

        // POST: VehicleTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TypeName")] VehicleType vehicleType)
        {
            if (id != vehicleType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicleType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleTypeExists(vehicleType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VehicleType == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // POST: VehicleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VehicleType == null)
            {
                return Problem("Entity set 'Garage_2_0Context.VehicleType'  is null.");
            }
            var vehicleType = await _context.VehicleType.FindAsync(id);
            if (vehicleType != null)
            {
                _context.VehicleType.Remove(vehicleType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleTypeExists(int id)
        {
          return (_context.VehicleType?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Garage 2.0/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage3._0.Core.Entities;
using Garage3._0.Core.ViewModels;
using Garage_2._0.Data;
using System.Globalization;

namespace Garage_2._0.Controllers
{
    public class UsersController : Controller
    {
        private readonly Garage_2_0Context _context;
        private DateTime dt;

        public UsersController(Garage_2_0Context context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.Select(v => new UserViewModel
            {
                Id = v.Id,
                UserName = v.UserName,
                Fname = v.Fname,
                Lname = v.Lname,
                Pnr = v.Pnr
            }).ToListAsync());

                //return _context.User != null ?
                //            View(await _context.User.ToListAsync()) :
                //            Problem("Entity set 'Garage_2_0Context.User'  is null.");
            }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            //var viewModel = new UserDetailViewModel
            //{
            //    Id = user.Id,
            //    UserName = user.UserName,
            //    Fname = user.Fname,
            //    Lname = user.Lname,
            //    Pnr = user.Pnr,

            //    Vehicles = user.Vehicles.Select(v => new Vehicle
                
            //    )
            //};

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Fname,Lname,Pnr")] User user)
        {
           if(ValidatePersNr(user.Pnr))
            {
                ModelState.AddModelError("Pnr", "Error! The personal number already exists!");
            }

            if (ModelState.IsValid)
            {
          
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        private bool ValidatePersNr(string pnr)
        {
            return _context.User.Any(u => u.Pnr == pnr);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Fname,Lname,Pnr")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.User == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.User == null)
            {
                return Problem("Entity set 'Garage_2_0Context.User' is null.");
            }
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return (_context.User?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [HttpGet]
        public JsonResult ValidatePerNum(string Pnr)
        {
            UInt64 i;
            string LuhnStr;

            if (UInt64.TryParse(Pnr, out i))
            {
                if (DateTime.TryParseExact(Pnr.Substring(0, Pnr.Length - 4), "yyyymmdd", CultureInfo.InvariantCulture, DateTimeStyles.None, out dt))
                {
                    LuhnStr = Pnr.Substring(2).Remove(9, 1); // Deletes the first 2 digits and the last digit (yyyymmddxxxx => yymmddxxx)                                                         
                    if (Luhn(LuhnStr) == Pnr[11] - '0')
                    {
                        //dt = DateParse(Pnr);
                        return Json(true);
                    }
                    else
                    {
                        return Json("Invalid personal number format");
                    }
                }
                else
                {
                    return Json("Invalid personal number format");
                }
            }
            else
                return Json("The personal number shall have only digits");
        }

        //private static DateTime DateParse(string Pnr)
        //{
        //    Pnr = Pnr.Remove(8, 4);
        //    int year = int.Parse(Pnr.Substring(0, 4));
        //    int month = int.Parse(Pnr.Substring(4,2));
        //    int day = int.Parse(Pnr.Substring(6, 2));

        //    DateTime date1 = new DateTime(year, month, day);

        //    return date1;

        //}

        private static int Luhn(string value)
        {
            // Luhm algorithm doubles every other number in the value.
            // To get the correct checksum digit we aught to append a 0 on the sequence.
            // If the result becomes a two digit number, subtract 9 from the value.
            // If the total sum is not a 0, the last checksum value should be subtracted from 10.
            // The resulting value is the check value that we use as control number.

            // The value passed is a string, so we aught to get the actual integer value from each char (i.e., subtract '0' which is 48).
            int[] t = value.ToCharArray().Select(d => d - 48).ToArray();
            int sum = 0;
            int temp;
            for (int i = 0; i < t.Length; i++)
            {
                temp = t[i];
                temp *= 2 - (i % 2);
                if (temp > 9)
                {
                    temp -= 9;
                }
                sum += temp;
            }
            sum =  ((int)Math.Ceiling(sum / 10.0)) * 10 - sum;
            return sum;
        }

        [HttpGet]
        public JsonResult ValidateName(string FName, string LName)
        {
            if (String.Equals(FName.ToLower(), LName.ToLower()))
                return Json("FirstName and LastName shall not be the same.");
            else
            {
                return Json(true);
            }

        }
    }
}

Garage 2.0/Views/Users/Create.cshtml
@model Garage3._0.Core.Entities.User

@{
    ViewData["Title"] = "Create";
}
<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
<h1 class="text-center">Register as member</h1>
<hr />
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2">
<div class="row">
    <div>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fname" class="control-label"></label>
                <input asp-for="Fname" class="form-control" />
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lname" class="control-label"></label>
                <input asp-for="Lname" class="form-control" />
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pnr" class="control-label"></label>
                <input asp-for="Pnr" class="form-control" placeholder="yyyymmddxxxx" />
                <span asp-validation-for="Pnr" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-success my-4 mx-3" /><a asp-controller="Vehicle" asp-action="Index" class="btn btn-dark">Go back to mainpage</a>
            </div>
        </form>
    </div>
</div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage 2.0/Views/Users/Delete.cshtml
@model Garage3._0.Core.Entities.User

@{
    ViewData["Title"] = "Delete";
}

<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
<h1 class="text-center">Delete</h1>

<hr />
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2">
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Fname)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Fname)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Lname)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Lname)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Pnr)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Pnr)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to userlist</a>
    </form>
</div>

Garage 2.0/Views/Users/Details.cshtml
@model Garage3._0.Core.ViewModels.UserDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
<h1 class="text-center">Details</h1>
<hr />
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2">
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Fname)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Fname)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Lname)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Lname)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Pnr)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Pnr)
        </dd>
    </dl>

    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pnr)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Vehicles) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParkingLot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeOfArrival)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-dark">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-dark">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        }
    </tbody>
    </table>



</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class=" btn btn-primary">Edit</a> |
    <a asp-action="Index" class=" btn btn-primary" >Back to userlist</a>
</div>
</div>
</div>

Garage 2.0/Views/Users/Edit.cshtml
@model Garage3._0.Core.Entities.User

@{
    ViewData["Title"] = "Edit";
}

<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
<h1 class="text-center">Edit</h1>
<hr />
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2">
<h4>User</h4>
<hr />
<div class="row">
    <div>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fname" class="control-label"></label>
                <input asp-for="Fname" class="form-control" />
                <span asp-validation-for="Fname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lname" class="control-label"></label>
                <input asp-for="Lname" class="form-control" />
                <span asp-validation-for="Lname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pnr" class="control-label"></label>
                <input asp-for="Pnr" class="form-control" />
                <span asp-validation-for="Pnr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary" >Back to userlist</a>
</div>
</div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage 2.0/Views/Users/Index.cshtml
@model IEnumerable<Garage3._0.Core.ViewModels.UserViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3 sectioncolors navbar-dark rounded-3">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Vehicle" asp-action="Admin">Vehicles in garage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Users" asp-action="Index">View Users</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="VehicleTypes" asp-action="Index">Vehicle Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Vehicle" asp-action="Statistics">Statistics</a>
                        </li>
                   </ul>
                </div>
        </nav> 
<h1 class="text-center">Users overview</h1>
<hr />
<div class="row">
    <div>

<p>
    <a asp-action="Create" class="btn btn-success">Create new user</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pnr)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pnr)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-dark">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-dark">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>
</div>