Garage 2.0/Models/EditVehicleViewModel.cs
using Garage3._0.Core.Entities;
using System.ComponentModel;

namespace Garage_2._0.Models
{
    public class EditVehicleViewModel
    {
        public int Id { get; set; }

        [DisplayName("Parking Lot")]
        public int ParkingLot { get; set; }

        [DisplayName("Registration number")]
        public string RegNr { get; set; } = String.Empty;

        [DisplayName("Type of vehicle")]
        public VehicleType VehicleType { get; set; }

        [DisplayName("Make")]
        public string Make { get; set; }

        [DisplayName("Model")]
        public string Model { get; set; }

        [DisplayName("Color")]
        public string Color { get; set; }

        [DisplayName("Wheels on vehicle")]
        public int NrOfWheels { get; set; }

        [DisplayName("Time parking started")]
        public DateTime TimeOfArrival { get; set; }

    }
}

Garage 2.0/Models/StatisticsViewModel.cs
using Garage3._0.Core.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Garage_2._0.Models
{
    public class StatisticsViewModel
    {
        public IEnumerable<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
       
        public string? Vehicle  { get; set; }
        
        public int VehiclesNoOfWheels { get; set; }

        public int Cost { get; set; }

        public IEnumerable<VehicleCountDto> VehicleCount { get; set; }
    }
}

Garage 2.0/Models/VehicleTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage_2._0.Data;
using Garage3._0.Core.Entities;
using Garage3._0.Core.ViewModels;

namespace Garage_2._0.Models
{
    public class VehicleTypesController : Controller
    {
        private readonly Garage_2_0Context _context;

        public VehicleTypesController(Garage_2_0Context context)
        {
            _context = context;
        }

        // GET: VehicleTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.VehicleType.Select(v => new VehicleTypeViewModel
            {
                Id = v.Id,
                TypeName = v.TypeName

            }).ToListAsync());

            //return _context.VehicleType != null ? 
            //              View(await _context.VehicleType.ToListAsync()) :
            //              Problem("Entity set 'Garage_2_0Context.VehicleType'  is null.");
        }

        // GET: VehicleTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VehicleType == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // GET: VehicleTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VehicleTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TypeName")] VehicleTypeViewModel vehicleView /*VehicleType vehicleType*/)
        {
            if (ModelState.IsValid)
            {
                var vehicleType = new VehicleType
                {
                    Id = vehicleView.Id,
                    TypeName = vehicleView.TypeName
                };

                _context.Add(vehicleType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleView);
        }

        // GET: VehicleTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VehicleType == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType.FindAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }

        // POST: VehicleTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TypeName")] VehicleType vehicleType)
        {
            if (id != vehicleType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicleType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleTypeExists(vehicleType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VehicleType == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // POST: VehicleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VehicleType == null)
            {
                return Problem("Entity set 'Garage_2_0Context.VehicleType'  is null.");
            }
            var vehicleType = await _context.VehicleType.FindAsync(id);
            if (vehicleType != null)
            {
                _context.VehicleType.Remove(vehicleType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleTypeExists(int id)
        {
          return (_context.VehicleType?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Garage 2.0/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage_2._0.Data;
using Garage_2._0.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Text.RegularExpressions;
using Garage3._0.Core.ViewModels;
using Garage3._0.Core.Entities;

namespace Garage_2._0.Controllers
{
    public class VehicleController : Controller
    {
        private readonly Garage_2_0Context _context;
        public readonly uint _capacity = 9;

        public VehicleController(Garage_2_0Context context)
        {
            _context = context;
        }

        // GET: Vehicle2
        public async Task<IActionResult> Index() 
        {
            //if (_context.Vehicle_old != null)
            //{
            //    var vehicles = await _context.Vehicle_old.ToListAsync();
            //    //ViewData["NrOfParkedVehicles"] = vehicles.Count;

            //    if (vehicles.Count == _capacity) ViewData["NrOfAvailableSlots"] = "The garage is full";
            //    else ViewData["NrOfAvailableSlots"] = _capacity - vehicles.Count;

            //    return View(vehicles);
            //}
            //else return Problem("Entity set 'Garage_2_0Context.Vehicle2'  is null.");

            return View(await _context.Vehicle.Select(v => new IndexViewModel
            {
                Fname = v.User.Fname,
                Lname = v.User.Lname,
                Id = v.Id,
                RegNr = v.RegNr,
                TimeOfArrival = v.TimeOfArrival,
                TypeName = v.VehicleType.TypeName,
                ParkingLot = v.ParkingLot
            }).ToListAsync());
                
            //return _context.Vehicle2 != null ?
            //            View(await _context.Vehicle2.ToListAsync()) :
            //            Problem("Entity set 'Garage_2_0Context.Vehicle2'  is null.");
        }

        // GET: Vehicle2/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle2 = await _context.Vehicle.Include(v => v.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle2 == null)
            {
                return NotFound();
            }

            return View(vehicle2);
        }

        // GET: Vehicle2/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehicle2/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RegNr,VehicleTypeId,Make,Model,Color,NrOfWheels,UserId")] Vehicle vehicle)
        {
            //if (RegNumExists(vehicle2.RegNr))
            //    ModelState.AddModelError("RegNr", "RegNr is already in the garage.");
            // return Problem("RegNr is already in the garage.");

            var vehicles = await _context.Vehicle.ToListAsync();

            if(vehicles.Count == _capacity)
                return Problem("Garage is Full");

            if (ModelState.IsValid)
            {
                vehicle.RegNr = vehicle.RegNr.ToUpper();
                vehicle.ParkingLot = GetParkingLot();

                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                TempData["Message"] = $"Vehicle with registration number {vehicle.RegNr} has been parked";
                return RedirectToAction(nameof(Index));
                
            }
            return View(vehicle);
        }

        // GET: Vehicle2/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehicle == null) return NotFound();

            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle == null) return NotFound();

            var viewModel = new Vehicle
            {
                Id = vehicle.Id,
                ParkingLot = vehicle.ParkingLot,
                RegNr = vehicle.RegNr,
                Make = vehicle.Make,
                Model = vehicle.Model,
                Color = vehicle.Color,
                NrOfWheels = vehicle.NrOfWheels,
                TimeOfArrival = vehicle.TimeOfArrival
            };
            
            //var viewModel = new EditVehicleViewModel
            //{
            //    RegNo = vehicle2.RegNr,
            //};

            return View(viewModel);
        }

        // POST: Vehicle2/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ParkingLot,RegNr,VehicleTypeId,Make,Model,Color,NrOfWheels,UserId")] EditVehicleViewModel vehicleView)
        {
            if (id != vehicleView.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var vehicle = new Vehicle
                    {
                        Id = vehicleView.Id,
                        ParkingLot = vehicleView.ParkingLot,
                        RegNr = vehicleView.RegNr,
                        Make = vehicleView.Make,
                        Model = vehicleView.Model,
                        Color = vehicleView.Color,
                        NrOfWheels = vehicleView.NrOfWheels,
                        TimeOfArrival = vehicleView.TimeOfArrival
                    };
                    
                    _context.Update(vehicle);
                    _context.Entry(vehicle).Property(v => v.TimeOfArrival).IsModified = false;
                    _context.Entry(vehicle).Property(v => v.RegNr).IsModified = false;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicleView.Id)) return NotFound();
                    else throw;
                }
                TempData["Message"] = $"Vehicle has been rebuilt";
                return RedirectToAction(nameof(Index));
            }

            return View(vehicleView);
        }

        // GET: Vehicle2/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehicle == null) return NotFound();

            var vehicle2 = await _context.Vehicle
                .FirstOrDefaultAsync(m => m.Id == id);

            if(vehicle2 == null) return NotFound();

            TimeSpan timespan = new TimeSpan();
            timespan = DateTime.Now.Subtract(vehicle2.TimeOfArrival);
            double cost = timespan.TotalMinutes * 0.9;

            int i = timespan.ToString().IndexOf(".");
            ViewBag.TimeParked = timespan.ToString().Remove(i);

            i = cost.ToString().IndexOf(",");
            ViewBag.Cost = cost.ToString().Remove(i + 3);

            return View(vehicle2);
        }

        // POST: Vehicle2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehicle == null)
            {
                return Problem("Entity set 'Garage_2_0Context.Vehicle2'  is null.");
            }
            var vehicle2 = await _context.Vehicle.FindAsync(id);
            if (vehicle2 != null)
            {
                _context.Vehicle.Remove(vehicle2);
            }
            
            await _context.SaveChangesAsync();
            TempData["Message"] = $"Vehicle has exited the garage";
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return (_context.Vehicle?.Any(e => e.Id == id)).GetValueOrDefault();
        }
  
        [HttpGet]
        public JsonResult ValidateRegNum(string regnr)
        {
            var r = new Regex("[A-Z][A-Z][A-Z][1-9][1-9][1-9]");
            if (!r.IsMatch(regnr.ToUpper()))
            {
                return Json("Invalid RegNr format");
            }
            else if ((_context.Vehicle?.Any(r => r.RegNr.ToUpper() == regnr.ToUpper())).GetValueOrDefault())
            {
                return Json("RegNr is already in the garage");
            }

            return Json(true);
        }

        private int GetParkingLot()
        {
            var vehicles = _context.Vehicle.ToList();
            int parkingLot = 0, i = 1;

            foreach (var vehicle in vehicles.OrderBy(p => p.ParkingLot).ToList())
            {
                if (vehicle.ParkingLot > parkingLot + 1) return parkingLot + 1;

                parkingLot = vehicle.ParkingLot;
                i++;
            }

            return i;
        }


        public async Task<IActionResult> Statistics()
        {
            if (_context.Vehicle == null)
            {
                return NotFound();
            }

            var totalCount = await Statistics_1_Async();
            var totalCount2 = await Statistics_2_Async();
            
            if (totalCount == null)
            {
                return NotFound();
            }

            var model = new StatisticsViewModel
            {
                VehicleCount = totalCount,
                VehiclesNoOfWheels = totalCount2
            };
            
            return View(model);
        }

        private async Task<List<VehicleCountDto>> Statistics_1_Async()
        {

            //Linq aggregate
          return await _context.VehicleType.Select(v => new VehicleCountDto

Garage 2.0/Views/Vehicle/Admin.cshtml
@model IEnumerable<IndexViewModel>

@{
    ViewData["Title"] = "Admin";
}

<div class="card rounded-3 listfunc border-0 p-3 pagecolors">

            <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3 sectioncolors navbar-dark rounded-3">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Vehicle" asp-action="Admin">Vehicles in garage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Users" asp-action="Index">View Users</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="VehicleTypes" asp-action="Index">Vehicle Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Vehicle" asp-action="Statistics">Statistics</a>
                        </li>
                   </ul>
                </div>
        </nav> 

<div class="container-fluid">

<div class="row sectioncolors">
<div class="col-3"></div>
<div class="card-title col-6 text-center">
    <h3 class="m-2">Current cars in garage</h3>
    <form asp-controller="Vehicle" asp-action="Admin2" method="get">
    <p>
        <input class="rounded-3 searchheight" type="text" name="SearchString" placeholder="Search" />
        <input class="btn btn-success rounded-3 text-white searchheight" type="submit" value="Search" />
    </p>
    </form> 
</div>
</div>
</div>
<div class="card-body whitebg">
<table class="table mb-5">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fname)
            </th>  
            <th>
                @Html.DisplayNameFor(model => model.Lname)
            </th>  
            <th>
                @Html.DisplayNameFor(model => model.ParkingLot)
            </th>            
            <th>
                @Html.DisplayNameFor(model => model.RegNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeName)
            </th>
       @*   <th>
                @Html.DisplayNameFor(model => model.Fname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NrOfWheels)
            </th>
            <th>*@
                @Html.DisplayNameFor(model => model.TimeOfArrival)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @*OrderBy(p => p.Fname).ToList())*@
@foreach (var item in Model.OrderBy(x => x.Fname).ThenBy(y=>y.Fname).ToList()){ 
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParkingLot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeName)
            </td>
@*          <td>
                @Html.DisplayFor(modelItem => item.Make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NrOfWheels)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.TimeOfArrival)
            </td>
@*            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>*@
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-dark">Visit workshop</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-dark">View vehicle</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Stop parking</a>
            </td>
        </tr>
}

    </tbody>
</table>
</div>
</div>

Garage 2.0/Views/Vehicle/Create.cshtml
@using Garage_2._0.Services
@model Vehicle
@inject IVehicleTypeSelectListService serviceVT
@inject IUserSelectListService serviceU

@{
    ViewData["Title"] = "Create";
}
<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
<h1 class="text-center">Park vehicle</h1>

<hr />
<div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2">
        <form asp-action="Create" asp-controller="Vehicle" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegNr" class="control-label"></label>
                <input asp-for="RegNr" class="form-control" />
                <span asp-validation-for="RegNr" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="VehicleType" class="control-label"></label>
                <select class="form-control" asp-for="VehicleType" asp-items="@Html.GetEnumSelectList<VehicleType>()">
                    <option selected="selected" value="">Select Vehicle Type</option>
                </select>
                <input asp-for="VehicleType" class="form-control" />
                <span asp-validation-for="VehicleType" class="text-danger"></span>
            </div>*@
            <div class="input-group-append">
                <label asp-for="VehicleTypeId" class="control-label"></label>
                <select class="form-control" asp-for="VehicleTypeId" asp-items="@await serviceVT.GetVehicleTypesAsync()">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="VehicleTypeId" class="text-danger"></span>
            </div>
            <div class="input-group-append">
                <label asp-for="User" class="control-label"></label>
                <select class="form-control" asp-for="UserId" asp-items="@await serviceU.GetUsersAsync()">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="User" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>*@
            <div class="form-group">
                <label asp-for="Make" class="control-label"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NrOfWheels" class="control-label"></label>
                <input asp-for="NrOfWheels" class="form-control" />
                <span asp-validation-for="NrOfWheels" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input id="parked" type="submit" value="Start parking" class="btn btn-success my-4 mx-3" /><a asp-action="Index" class="btn btn-dark">Go back to mainpage</a>
            </div>
        </form>
    </div>
</div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage 2.0/Views/Vehicle/Delete.cshtml
@*@model Garage_2._0.Models.Vehicle_old*@
@model Vehicle

@{
    ViewData["Title"] = "Delete";
}

<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
<h1>Stop parking</h1>

<h3></h3>
<div>
    <h4 class="mt-4">Receipt</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParkingLot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParkingLot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegNr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegNr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeOfArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeOfArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User.Fname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Fname)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.Raw("Time Parked")
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.TimeParked
        </dd>
        <dt class = "col-sm-2">
            @Html.Raw("Cost EUR")
        </dt>
        <dd class = "col-sm-10">
            @ViewBag.Cost
        </dd>
@*        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)  
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NrOfWheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NrOfWheels)
        </dd>*@
    </dl>
    
    <p class="mt-5">Are you sure you wish to end your parking session?</p>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Stop parking" class="btn btn-danger mx-3" /><a asp-controller="Vehicle" asp-action="Admin" class="btn btn-dark">Go back to vehiclelist</a>
    </form>

</div>
</div>

Garage 2.0/Views/Vehicle/Statistics.cshtml
@model StatisticsViewModel

@{
	ViewData["Title"] = "Statistics";
}
<div class="card rounded-3 listfunc border-0 p-3 pagecolors">
	    <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3 sectioncolors navbar-dark rounded-3">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Vehicle" asp-action="Admin">Vehicles in garage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Users" asp-action="Index">View Users</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="VehicleTypes" asp-action="Index">Vehicle Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success ms-2" asp-area="" asp-controller="Vehicle" asp-action="Statistics">Statistics</a>
                        </li>
                   </ul>
                </div>
        </nav> 

	<h1>Statistics</h1>

	<div>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.Raw("Vehicle Type:")
			</dt>
			<dd class="col-sm-10">
				@Html.Raw("Count")
			</dd>
			<hr class= "bg-dark"/>
			@foreach (var vehicleCount in Model.VehicleCount)
			{
				<dt class="col-sm-2">
					<p>@vehicleCount.VehicleType</p>
				</dt>
				<dd class="col-sm-10">
					<p>@vehicleCount.Total</p>
				</dd>
			}
		</dl>
	</div>
	<div>
		<hr class = "bg-dark"/>
		<dl class = "row">
			<dt class="col-sm-2">
				@Html.Raw("Number of wheels:")
			</dt>
			<dd class="col-sm-10">
				@Model.VehiclesNoOfWheels
			</dd>
		</dl>
	</div>
</div>